version: '3'

services:
  dash-auth-flask:
    container_name: dash-auth-flask
    restart: always
    volumes:
      - ./dash-auth-flask:/app
    environment:
      - FLASK_APP=app:server
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    command: >
      sh -c "python create_tables.py &&
             flask run --host=0.0.0.0 --port=8000"