version: '3'

services:
  dash-auth-flask:
    container_name: dash-auth-flask
    restart: always
    build: ./dash-auth-flask
    image: dash-flask-image
    ports:
      - "8000:8000"
    command: >
      sh -c "python create_tables.py &&
             /usr/local/bin/gunicorn -w 1 -b :8000 app:server"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash-auth-flask